"use client"
import './globals.css'
import { Inter } from 'next/font/google'
import Wagmi from '@/app/wagmi'
import { WalletConnectModalSign } from '@walletconnect/modal-sign-react'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'One Mail',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Wagmi>
        {children}
        <WalletConnectModalSign
        projectId='197d6cc2a7a2f1af71cb513ee3120946'
        metadata={{
          name: 'My Dapp',
          description: 'My Dapp Description',
          url: 'mydapp.com',
          icons: ['https://mydapp-logo.png']
        }}
      />
        </Wagmi></body>
    </html>
  )
}
